### ISSUE TITLE
Set up continuous benchmarking

### ISSUE THREAD

**Issue by kbara** [Igalia/snabb#110]
It would be awesome to always know:
- how the system's performance is on the current dev branch on sample workloads
- if we have performance regressions with new commits

**Comment by andywingo** [comment]
Yes!!! Once we have our test machines installed at the office we can do this like snabb-bot does (an external continuation integration tool).

**Comment by andywingo** [comment]
See https://github.com/SnabbCo/snabbswitch/issues/688

**Comment by eugeneia** [comment]
Would you be interested in running the second [SnabbBot](https://github.com/SnabbCo/snabbswitch/blob/master/src/doc/testing.md#running-a-snabbbot-ci-instance) instance?

**Comment by andywingo** [comment]
@eugeneia yes certainly!  we have two machines that are pretty much the same as interlaken and which are mostly idle.  Do you have a NixOS config that automatically runs the SnabbBot?

**Comment by eugeneia** [comment]
@wingo I have hacked together a NixOS module that runs SnabbBot as a service (configurable through Nix options): https://gist.github.com/eugeneia/53fe2615c1e90bc778a1

Is that what you were looking for? This is my first Nix expression, so take it with a grain of salt.

**Comment by dpino** [comment]
Closing ticket as continuous benchmarking of the lwAFTR is currently deployed at:

https://hydra.snabb.co/project/igalia

A detailed description of continuous benchmarking of the lwAFTR can be checked at https://github.com/Igalia/snabb/blob/lwaftr/src/program/lwaftr/doc/continuous-integration.md
