### ISSUE TITLE
Channels mechanism not robust to /var/run/snabb/PID already existing

### ISSUE THREAD

**Issue by wingo** [Igalia/snabb#268]
Kat was just running a test and started to get bizarro segfaults doing simple things like:

```
./snabb-lwaftr bench \
   program/lwaftr/tests/data/icmp_on_fail.conf \
   program/lwaftr/tests/data/tcp-frominet-bound.pcap \
   program/lwaftr/tests/data/tcp-fromb4-ipv6.pcap
```

Unfortunately we don't know what git revision the build corresponds to because reasons.  Anyway, the snabb runs were failing with:

```
zsh: bus error (core dumped)  ./snabb-lwaftr bench ...
```

Removing the contents of `/var/run/snabb` "fixed" the problem.

Relatedly, we have seen exceptions on startup if the channels directory for a PID was already there.  I suspect channels somehow in this issue, as we haven't seen this failure mode in other contexts, and in this one, we got this error before we started seeing the segfaults:

```
apps/lwaftr/channel.lua:51: error creating file "/var/run/snabb/2876/channels/lwaftr/control": File exists
```

This bug, then, is to first reproduce the issue simply by running a lot of snabb check processes, until we get the error creating the file.  Then see if we can reproduce the segfault.  It's probably due to the file not being mapped correctly or something.  Then we fix.

**Comment by kbara** [comment]
The revision was e525074bc82627b36dcc02752fb064eab95ef911 - this was after I'd built on your code from #266 .

Possibly unrelated, possibly not, here's an intermittent error I had several snabb launches before this appeared:
```
Testing: from-to-b4 IPv6 packet, with hairpinning
apps/lwaftr/channel.lua:51: error creating file "/var/run/snabb/2876/channels/lwaftr/control": File exists
stack traceback:
	core/main.lua:122: in function <core/main.lua:120>
	[C]: in function 'error'
	apps/lwaftr/channel.lua:51: in function 'create_ring_buffer'
	apps/lwaftr/channel.lua:169: in function 'create'
	apps/lwaftr/lwaftr.lua:205: in function 'new'
	core/app.lua:165: in function <core/app.lua:162>
	core/app.lua:201: in function 'apply_config_actions'
	core/app.lua:110: in function 'configure'
	program/lwaftr/check/check.lua:29: in function 'run'
	program/lwaftr/lwaftr.lua:17: in function 'run'
	core/main.lua:41: in function <core/main.lua:32>
	[C]: in function 'xpcall'
	core/main.lua:151: in main chunk
	[C]: at 0x0044ff50
	[C]: in function 'pcall'
	core/startup.lua:1: in main chunk
	[C]: in function 'require'
	[string "require "core.startup""]:1: in main chunk
cmp: /tmp/endoutv4.pcap: No such file or directory
-rw-rw-r-- 1 me me 24 Feb 10 23:36 ../data/empty.pcap
ls: cannot access /tmp/endoutv4.pcap: No such file or directory
Failure: ../../../../snabb-lwaftr check ../data/no_icmp.conf ../data/empty.pcap ../data/tcp-fromb4-tob4-ipv6.pcap ../data/empty.pcap ../data/recap-ipv6.pcap
```

After that, I re-ran the end-to-end tests, and several ran successfully before a failure occurred. After that failure, all invocations of snabb-lwaftr that did more than show help failed, presumably with the bus error shown above.

**Comment by dpino** [comment]
Closing as the bug refers to an use of channels that it's no longer supported.

In v2, a channel was used to send actions to the lwAFTR data-plane via the "control" subcommand (for instance, reload-binding-table or dump-binding-table). A lwAFTR had access to a ring-buffer (channel) exposed as shared memory. The bug happened when creating a channel in the lwAFTR data-plane.

In v3, the channel code has been refactored and it's now used only for leader/follower communication. Since the data-plane no longer features a channel, this error doesn't happen anymore when running the end-to-end tests.
