### ISSUE TITLE
Implement NS retries in NDP

### ISSUE THREAD

**Issue by dpino** [Igalia/snabb#292]
When 'next_hop_ipv6_addr' is set in a lwaftr.conf file, the NDP application sends a NS (neighbor solicitor) request broadcast to resolve the IPv6 address to an Ethernet address. The NDP send this solicatation only once, so in the event that the Neighbor Advertisement reply is missed, the IPv6 address won't be resolved into an Ethernet address.

Sending 3 or 5 five solications should guarantee non NA reply is missed.

**Comment by dpino** [comment]
Related with https://github.com/Igalia/snabbswitch/pull/291

**Comment by kbara** [comment]
Multiple solicitations aren't a guarantee (ie, a down link could come up after 6 seconds), and there are some subtleties with override flags, but this is an important step.

**Comment by dpino** [comment]
Solved in #294.
