### ISSUE TITLE
Rewrite lwstats.py in Lua, make it read the new CSV output format

### ISSUE THREAD

**Issue by aperezdc** [Igalia/snabb#71]
The `tests/apps/lwaftr/end-to-end/lwstats.py` script does not have anything Python-specific that couldn't be written in Lua. Provided that people may want to use it in the same machine where Snabb is running, and that Snabb itself does not have a dependency on Python, it could be that Python is not available, and therefore it would be good to rewrite the script in Lua.

Also, currently the output format of the statistics is done in CSV format, so the new version of the script should read that as input.

**Comment by kbara** [comment]
I believe the script as-is obsolete, since we've removed nic_ui.lua/tooling which generates this output format. We can scrap it entirely or teach (the port of it) to parse the new CSV output, but porting the current one would be a mistake.

**Comment by aperezdc** [comment]
@kbara Very good point. Luckily I got dragged into other things so it won't be needed to throw away much code (if any). I have edited the issue title and description accordingly.

**Comment by andywingo** [comment]
Does this script provide any value currently?  I think maybe not, given that we identified the NUMA issues which caused so much instability in our numbers...

**Comment by kbara** [comment]
In broken form, no. Unbroken, it would still be useful - it was a very handy way to get an idea of whether small performance increases were real by checking multiple runs, and the transient tooling does not provide an equivalent.

**Comment by aperezdc** [comment]
Quick update: this is still stalled from my side. This does not seem to be a pressing issue, so I have been working in other issues (mostly, IPv4 reassembly), and will retake this afterwards.

**Comment by dpino** [comment]
Agreed with @aperezdc to close this issue.
